### ISSUE TITLE
Isnt this redundant of the Ferma project? merge projects?

### ISSUE THREAD

**Issue by freemo** [karthicks/gremlin-ogm#2]
Hi I'm the author of the Ferma project ( https://github.com/Syncleus/Ferma ).

This project seems to be almost completely redundant of the functionality already present in the Ferma project. The annotation names are a bit different, as are the method calls, but they both seem to be virtually identical in what they are trying to accomplish and how they go about it. Ferma however is more mature so has a much more extensive set of features.

With that said I was wondering if you'd be interested in merging efforts, if there is anything novel in your code I've overlooked I'd love to add that functionality to Ferma and perhaps work together rather than working separately towards the same end goal. Let me know if this would interest you.

**Comment by freemo** [comment]
@karthicks Sorry forgot to tag you in the issue ^^^

**Comment by karthicks** [comment]
Hi, @freemo ,

Thanks for taking a look at this project. Truth be told, I wasn't even aware of `Ferma` project when I was implementing this. While it's true that they're both object graph mappers, I see some subtle yet key differences in terms of not only the annotations but the way the properties are specified (untyped vs annotated), how the vertices and edges are coupled together, etc, which makes me hesitate attempting a merge of the two projects. I don't it would be a trivial task, in my opinion.

Regards,
Karthick

**Comment by freemo** [comment]
@karthicks Great start to a project you have here. Honestly I'm less interested in merging the codebase as I am about merging ideas and perhaps effort. Those subtle differences in ideology may be important and I'd love to see us work together and bring our ideas together in a way that creates the best of both worlds. Even if the code itself wouldnt merge to well that doesnt meant our mutual ideas cant coexist in a single project.

Just seems to make sense to me rather than have two similar projects with two independent efforts to pool our future man-hours into one unified effort that could be better than either individual effort could achieve on its own.
