### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by sturner** [karthicks/gremlin-ogm#5]
This looks to have promise and I may be doing some graph DB stuff in the future . .

**Comment by charbull** [comment]
Hey @sturner did you get an answer for this?

**Comment by karthicks** [comment]
Sorry about the delayed response. For some reason, I'm not getting notified of issues on this project. 

Long story short, this repository is an older, albeit stable, version of the code that is currently deployed at the company I work for. It's a little behind in terms of certain features, but I can add that if someone sees a need for it.

Needless to say, I would welcome pull requests that build on the project.
